# -*- coding: utf-8 -*-
"""decisiontree_iris.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hTe7HuYmCOJXPkr2eFRwUAy4l5uKk8Ry
"""

from sklearn.datasets import load_iris
import matplotlib.pyplot as plt
from sklearn.tree import DecisionTreeClassifier 
from sklearn.metrics import accuracy_score

#   now loading IRIS only
iris=load_iris()

dir(iris)   #exloring variable

#iris.DESCR these are features name
iris.feature_names

#   label or answer
iris.target_names

#actual data with attributes
features=iris.data
features.shape
type(features)

# now time for target or label data that will be same as no. of features
label=iris.target
label.shape

SL=features[0:,0]

SW=features[0:,1]

plt.xlabel("Sepal_length")
plt.ylabel("Sepal_width")
plt.scatter(SL,SW,label="sepal data",marker='*')
plt.scatter(features[0:,2],features[0:,3],label="sepal width",marker='x')
plt.grid()
plt.legend()

#  now time for seperating data into two categories
#   1.---training data
#    2.--- testing data -- questions
from sklearn.model_selection  import train_test_split
train_data,test_data,label_train,label_test=train_test_split(features,label,test_size=0.1)

# calling decsiontree classifier
clf=DecisionTreeClassifier()

#   now time for training clf
trained=clf.fit(train_data,label_train)

#  now predicting flowers
predicted_flowers=trained.predict(test_data)

predicted_flowers    #algo answer

label_test    #actual answer

#  find accuracy score
accuracy_score(label_test,predicted_flowers)

